version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    restart: always
    command: gunicorn -w 4 --bind 0.0.0.0:8080 run:app
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - image-operations

networks:
  my-network: